;;; gtd-review-test.el --- Archive-aware review tests -*- lexical-binding: t; -*-
(require 'ert)
(require 'org)
(require 'org-clock)
(load-file (expand-file-name "lisp/nowis-gtd.el" user-emacs-directory))

(ert-deftest gtd-review-includes-archives-and-clips-cross-day-clocks ()
  (let* ((dir (make-temp-file "gtd-review-test-" t))
         (active (expand-file-name "action.org" dir))
         (archive (expand-file-name "gtd_archive" dir))
         (org-todo-keywords '((sequence "TODO" "STARTED" "|" "DONE")))
         (date (format-time-string "%Y-%m-%d"))
         (yesterday (format-time-string "%Y-%m-%d" (org-time-from-absolute (1- (org-today)))))
         (files (list active archive)))
    (unwind-protect
        (save-window-excursion
          (with-temp-file active
            (insert (format "* DONE Completed\nCLOSED: [%s 10:30]\n:LOGBOOK:\nCLOCK: [%s 10:00]--[%s 10:30] => 0:30\n:END:\n* STARTED Ongoing\n:LOGBOOK:\nCLOCK: [%s 11:00]--[%s 11:20] => 0:20\n:END:\n" date date date date date)))
          (with-temp-file archive
            (insert (format "* DONE Archived\nCLOSED: [%s 00:15]\n:PROPERTIES:\n:ARCHIVE_OLPATH: Project A\n:END:\n:LOGBOOK:\nCLOCK: [%s 23:45]--[%s 00:15] => 0:30\n:END:\n" date yesterday date)))
          (let ((org-agenda-files (list active))
                (org-archive-location (concat archive "::datetree/"))
                (nowis/gtd-extra-archive-files nil))
            (nowis/review-done-by-project 1)
            (set-buffer "*Review by Project*")
            (let ((text (buffer-string)))
              (should (string-match-p "Time Spent" text))
              (should (string-match-p "Ongoing" text))
              (should (string-match-p "Archived" text))
              (should (string-match-p "1:05" text))
              (should (string-match-p "\\*\\* Project A" text))
              (should (= nowis/review-days 1))
              (nowis/review-refresh)
              (set-buffer "*Review by Project*")
              (should (string-match-p "1:05" (buffer-string))))
            ;; Move the completed task into the archive: totals stay the same.
            (with-temp-file active
              (insert (format "* STARTED Ongoing\n:LOGBOOK:\nCLOCK: [%s 11:00]--[%s 11:20] => 0:20\n:END:\n" date date)))
            (with-temp-buffer
              (insert-file-contents archive)
              (goto-char (point-max))
              (insert (format "* DONE Completed\nCLOSED: [%s 10:30]\n:LOGBOOK:\nCLOCK: [%s 10:00]--[%s 10:30] => 0:30\n:END:\n" date date date))
              (write-region (point-min) (point-max) archive nil 'silent))
            (dolist (file files) (with-current-buffer (find-file-noselect file) (revert-buffer t t)))
            (set-buffer "*Review by Project*")
            (nowis/review-refresh)
            (set-buffer "*Review by Project*")
            (should (string-match-p "1:05" (buffer-string)))))
      (dolist (file files) (when (get-file-buffer file) (kill-buffer (get-file-buffer file))))
      (when (get-buffer "*Review by Project*") (kill-buffer "*Review by Project*"))
      (delete-directory dir t))))

(ert-deftest gtd-review-escapes-brackets-in-task-links ()
  (with-temp-buffer
    (org-mode)
    (setq buffer-file-name "/tmp/review [test].org")
    (insert "* DONE [inbox] 拆出主线的验证策略\nCLOSED: [2026-10-04 Sun 15:01]\n")
    (goto-char (point-min))
    (let ((line (cdr (nowis/review--entry))))
      (erase-buffer)
      (insert line)
      (goto-char (point-min))
      (search-forward "[[")
      (backward-char 2)
      (let ((link (org-element-context)))
        (should (eq (org-element-type link) 'link))
        (should (equal (org-element-property :type link) "file"))
        (should (equal (org-element-property :search-option link)
                       "*[inbox] 拆出主线的验证策略"))
        (should (equal (buffer-substring-no-properties
                        (org-element-property :contents-begin link)
                        (org-element-property :contents-end link))
                       "[inbox] 拆出主线的验证策略"))))))

(ert-deftest gtd-review-all-history-includes-undated-done ()
  (let* ((file (make-temp-file "review-all-" nil ".org"))
         (org-agenda-files (list file))
         (org-archive-location "missing-archive::")
         (nowis/gtd-extra-archive-files nil))
    (unwind-protect
        (save-window-excursion
          (with-temp-file file
            (insert "* DONE Old\nCLOSED: [2000-01-01 Sat 12:00]\n:LOGBOOK:\nCLOCK: [2000-01-01 Sat 11:30]--[2000-01-01 Sat 12:00] => 0:30\n:END:\n* DONE Undated task\n* TODO Pending\n"))
          (nowis/review-done-by-project 'all)
          (with-current-buffer "*Review by Project*"
            (should (eq nowis/review-days 'all))
            (should (string-match-p "Undated task" (buffer-string)))
            (should (string-match-p "0:30" (buffer-string)))
            (should-not (string-match-p ":tstart" (buffer-string)))
            (nowis/review-refresh)
            (should (string-match-p "Undated task" (buffer-string)))))
      (when (get-file-buffer file) (kill-buffer (get-file-buffer file)))
      (when (get-buffer "*Review by Project*") (kill-buffer "*Review by Project*"))
      (delete-file file))))
