;;; nowis-ghostel-test.el --- Ghostel browsing regression tests -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'nowis-ghostel)

(ert-deftest nowis-ghostel-normal-leaves-char-on-alt-screen ()
  (with-temp-buffer
    (let ((ghostel--term t)
          (ghostel--input-mode 'char)
          (ghostel--pending-initial-line-mode t)
          (calls 0))
      (cl-letf (((symbol-function 'ghostel-alt-screen-p) (lambda () t))
                ((symbol-function 'ghostel-line-mode)
                 (lambda (&rest _) (ert-fail "Normal must not enter line mode")))
                ((symbol-function 'ghostel-emacs-mode)
                 (lambda () (cl-incf calls) (setq ghostel--input-mode 'emacs))))
        (nowis-ghostel--enter-emacs-mode)
        (nowis-ghostel--enter-emacs-mode)
        (should (eq ghostel--input-mode 'emacs))
        (should-not ghostel--pending-initial-line-mode)
        (should (= calls 1))))))

(ert-deftest nowis-ghostel-normal-preserves-copy-mode ()
  (with-temp-buffer
    (let ((ghostel--term t)
          (ghostel--input-mode 'copy))
      (cl-letf (((symbol-function 'ghostel-emacs-mode)
                 (lambda () (ert-fail "Do not unfreeze a user's selection"))))
        (nowis-ghostel--enter-emacs-mode)
        (should (eq ghostel--input-mode 'copy))))))

(ert-deftest nowis-ghostel-normal-sync-waits-for-terminal ()
  (with-temp-buffer
    (let ((ghostel--term nil)
          (ghostel--input-mode 'semi-char)
          (meow-normal-mode t)
          (calls 0))
      (cl-letf (((symbol-function 'ghostel-emacs-mode)
                 (lambda () (cl-incf calls) (setq ghostel--input-mode 'emacs))))
        (nowis-ghostel--sync-normal-mode)
        (should (= calls 0))
        (setq ghostel--term t)
        (nowis-ghostel--sync-normal-mode)
        (should (= calls 1))
        (setq meow-normal-mode nil ghostel--input-mode 'char)
        (nowis-ghostel--sync-normal-mode)
        (should (eq ghostel--input-mode 'char))))))

(ert-deftest nowis-ghostel-setup-installs-browsing-hooks ()
  (with-temp-buffer
    (let ((ghostel--term nil))
      (nowis-ghostel--set-up-meow)
      (should-not ghostel-readonly-fast-exit)
      (should (local-variable-p 'ghostel-readonly-fast-exit))
      (should (memq #'ghostel-char-mode meow-insert-enter-hook))
      (should (memq #'nowis-ghostel--enter-emacs-mode meow-insert-exit-hook))
      (should (memq #'nowis-ghostel--sync-normal-mode pre-command-hook)))))

(ert-deftest nowis-ghostel-browsing-moves-point-and-copies-region ()
  (with-temp-buffer
    (insert "first line\nsecond line\n")
    (let ((ghostel--term nil))
      (nowis-ghostel--set-up-meow))
    (use-local-map (ghostel--readonly-keymap))
    (setq buffer-read-only t)
    (setq-local ghostel--input-mode 'emacs)
    (let ((meow--selection nil)
          (meow-use-clipboard nil)
          (select-enable-clipboard nil)
          (select-enable-primary nil)
          (transient-mark-mode t)
          (kill-ring nil))
      (goto-char 8)
      (meow-left)
      (should (= (point) 7))
      (push-mark 1 t t)
      (meow-save)
      (should (equal (car kill-ring) "first "))
      (should (eq ghostel--input-mode 'emacs))
      (should (eq (key-binding (kbd "M-w")) #'ghostel-readonly-copy)))))

(provide 'nowis-ghostel-test)
;;; nowis-ghostel-test.el ends here
