;;; capsule.el --- Minimal package manager -*- lexical-binding: t; -*-

;; A ultra-simplified replacement for borg.
;; Git owns versions; Capsule prepares, compiles, and activates local packages.

(require 'cl-lib)
(require 'subr-x)

(defvar capsule-drones-directory
  (expand-file-name "lib/" user-emacs-directory)
  "Directory containing package subdirectories.")

(defvar capsule-compile-directories '("elisp" "lisp" "extensions" "sources")
  "Whitelist of subdirectories to compile and load.")

(defvar capsule-skip-autoloads-packages '("reader")
  "List of package names to skip when generating autoloads.
Each element should be a package name (string) as it appears in lib/ directory.")

(defvar capsule--config nil
  "Configuration snapshot dynamically shared within one Capsule operation.")

;;; Runtime: Initialize packages

;;;###autoload
(defun capsule-initialize ()
  "Activate lib/ packages, then load the generated local Lisp autoloads.
Startup only loads existing autoload files; generation belongs to the build."
  (let ((capsule--config (capsule--read-config)))
    ;; Autoload forms may require other packages, so install all paths first.
    (capsule--setup-load-path-all)
    (let ((pkg-dirs (capsule--package-directories)))
      (dolist (pkg-dir pkg-dirs)
	(let* ((pkg-name (file-name-nondirectory pkg-dir))
               (autoloads-file (expand-file-name
				(format "%s-autoloads.el" pkg-name) pkg-dir)))
          (when (file-exists-p autoloads-file)
            (condition-case err
		(load autoloads-file nil t)
              (error (message "Error loading %s: %S" autoloads-file err))))))
      (let ((autoloads (expand-file-name "lisp/lisp-autoloads.el" user-emacs-directory)))
        (if (file-exists-p autoloads)
            (load autoloads nil t)
          (display-warning 'capsule "Local autoloads missing; run make autoloads.")))
      (message "Capsule: Initialized %d packages" (length pkg-dirs)))))

(defun capsule-generate-local-autoloads ()
  "Generate local Lisp entry points without scanning tests or compiling files."
  (require 'loaddefs-gen)
  (let* ((dir (expand-file-name "lisp" user-emacs-directory))
         (default-directory dir))
    (when (file-directory-p dir)
      (let ((output (expand-file-name "lisp-autoloads.el" dir)))
        ;; A fresh output also removes entries for deleted source files.
        (when (file-exists-p output) (delete-file output))
        (loaddefs-generate (list dir) output (list output)
                           ";; Generated by Capsule; safe for capsule-batch-clean.\n"
                           nil t)))))

;;; Build-time: Batch functions (called from Makefile)

(defun capsule--package-directories ()
  "Return package directories in stable order for both activation and builds."
  (cl-remove-if-not #'file-directory-p
                    (directory-files capsule-drones-directory t "^[^.]")))

(defun capsule--should-compile-p (file)
  "Return non-nil if FILE should be compiled."
  (let ((filename (file-name-nondirectory file)))
    (and (string-suffix-p ".el" filename)
         (not (string-prefix-p "." filename))
         (not (string-suffix-p "-autoloads.el" filename))
         (not (string-suffix-p "-pkg.el" filename))
         (not (string-suffix-p "-test.el" filename))
         (not (string-suffix-p "-tests.el" filename)))))

(defun capsule--collect-el-files (dir)
  "Collect .el files directly in selected directories, without recursion.
Match the load-path and autoload scope; optional nested extensions stay opt-in."
  (cl-remove-if-not
   #'capsule--should-compile-p
   (delete-dups
    (cl-mapcan (lambda (directory)
                 (directory-files directory t "^[^.].*\\.el\\'"))
               (capsule--get-package-dirs dir)))))

(defun capsule--get-package-dirs (package)
  "Get PACKAGE's root, default subdirectories and extra .gitmodules load-path.
Explicit paths are additive and shared by activation, autoloads and compilation."
  (let* ((pkg-dir (directory-file-name
                   (expand-file-name package capsule-drones-directory)))
         (scan-dirs (list pkg-dir)))
    (dolist (subdir capsule-compile-directories)
      (let ((path (directory-file-name (expand-file-name subdir pkg-dir))))
        (when (file-directory-p path) (push path scan-dirs))))
    (dolist (subdir (capsule--package-config-values pkg-dir "load-path"))
      (let ((path (directory-file-name (expand-file-name subdir pkg-dir))))
        (unless (and (file-directory-p path) (file-in-directory-p path pkg-dir))
          (error "Capsule: Invalid load-path %S for %s (must be an existing directory inside the package)"
                 subdir pkg-dir))
        (push path scan-dirs)))
    (delete-dups (nreverse scan-dirs))))

(defun capsule--read-config ()
  "Read .gitmodules once into path-to-prefix and key-to-values tables.
Git handles quoting; NUL records preserve newlines in command values."
  (let ((modules (expand-file-name ".gitmodules" user-emacs-directory))
        (paths (make-hash-table :test #'equal))
        (values (make-hash-table :test #'equal)))
    (when (file-exists-p modules)
      (with-temp-buffer
        (let* ((default-directory user-emacs-directory)
               (status (process-file "git" nil '(t t) nil "config" "--file"
                                     modules "--null" "--list")))
          (unless (equal status 0)
            (error "Capsule: Cannot read %s (exit %s): %s"
                   modules status (buffer-string))))
        (dolist (record (split-string (buffer-string) "\0" t))
          (when (string-match "\n" record)
            (let ((key (substring record 0 (match-beginning 0)))
                  (value (substring record (1+ (match-beginning 0)))))
              (puthash key (cons value (gethash key values)) values))))
        (maphash
         (lambda (key entries)
           (setq entries (nreverse entries))
           (puthash key entries values)
           (when (string-match "\\`submodule\\..+\\.path\\'" key)
             (puthash (directory-file-name
                       (expand-file-name (car (last entries)) user-emacs-directory))
                      (substring key 0 -4) paths)))
         values)))
    (cons paths values)))

(defun capsule--package-config-values (pkg-dir field)
  "Return FIELD values for PKG-DIR from the current operation's snapshot."
  (when-let* ((prefix (gethash (directory-file-name (expand-file-name pkg-dir))
                               (car capsule--config))))
    (gethash (concat prefix field) (cdr capsule--config))))

(defun capsule--skip-build-p (pkg-dir)
  "Return non-nil when PKG-DIR opts out of bulk builds via skip-build = true."
  (equal (car (last (capsule--package-config-values pkg-dir "skip-build")))
         "true"))

(defun capsule--run-pre-build-command (pkg-dir)
  "Run PKG-DIR's trusted .gitmodules Shell command before scanning sources.
Only explicit builds call this; a failed command stops the package build.
The command runs on every build, so it should be safe to repeat."
  (let ((command (car (last (capsule--package-config-values
                             pkg-dir "pre-build-command")))))
    (when (and command (not (string-empty-p command)))
      (let ((default-directory (file-name-as-directory pkg-dir)))
        (message "Capsule: %s: %s" pkg-dir command)
        (capsule--run-process shell-file-name shell-command-switch command)))))

(defun capsule--prepare-package (pkg-dir)
  "Run the pre-build command and generate autoloads using the operation's config."
  (capsule--run-pre-build-command pkg-dir)
  (require 'loaddefs-gen)
  (let* ((pkg-name (file-name-nondirectory (directory-file-name pkg-dir)))
         (autoloads-file (expand-file-name (format "%s-autoloads.el" pkg-name) pkg-dir))
         (scan-dirs (capsule--get-package-dirs pkg-dir)))
    (message " Creating %s..." autoloads-file)
    (let ((default-directory pkg-dir))
      (loaddefs-generate scan-dirs autoloads-file nil
                         ";; Generated by Capsule; safe for capsule-batch-clean.\n"))))

(defvar capsule-use-native-compile nil
  "Whether to use native compilation instead of byte compilation.")

(defun capsule--compile-package (pkg-dir)
  "Compile Elisp files in PKG-DIR except .gitmodules no-byte-compile paths.
Repeated entries are literal paths relative to the package root and exclude
both byte and native compilation, but do not remove existing artifacts."
  (require 'bytecomp)
  (when capsule-use-native-compile (require 'comp))
  (let* ((byte-compile-warnings '(not free-vars unresolved))
         (excluded (mapcar (lambda (path) (expand-file-name path pkg-dir))
                           (capsule--package-config-values pkg-dir "no-byte-compile")))
         (files (cl-remove-if (lambda (file) (member file excluded))
			      (capsule--collect-el-files pkg-dir))))
    (dolist (file files)
      ;; Native compilation signals failures but may return nil for skipped files.
      (let ((result (funcall (if capsule-use-native-compile
                                 #'native-compile #'byte-compile-file) file)))
        (unless (or capsule-use-native-compile result)
          (error "Capsule: Byte compilation failed: %s" file))))))

(defun capsule--setup-load-path-all ()
  "Add all packages and their whitelisted subdirectories to load-path."
  (setq load-path
        (delete-dups
         (append (cl-mapcan #'capsule--get-package-dirs
                            (capsule--package-directories))
                 (cons (directory-file-name (expand-file-name "themes" data-directory))
                       load-path)))))

(defun capsule--check-native (native)
  "Reject unsupported native compilation before any preparation or compilation."
  (when (and native (not (and (fboundp 'native-comp-available-p)
                             (native-comp-available-p))))
    (error "Capsule: NATIVE=1 requires an Emacs built with native compilation")))

(defun capsule-batch-prepare (&optional native)
  "Run pre-build commands and generate autoloads for all packages.
This function is meant to be called from Emacs --batch mode."
  (unless noninteractive
    (error "capsule-batch-prepare is only for batch mode"))

  (capsule--check-native native)
  (let ((capsule--config (capsule--read-config)))
    (dolist (pkg-dir (capsule--package-directories))
      (let ((pkg-name (file-name-nondirectory pkg-dir)))
        (if (or (member pkg-name capsule-skip-autoloads-packages)
                (capsule--skip-build-p pkg-dir))
            (message "\n--- [%s] (skipped) ---\n" pkg-name)
          (message "\n--- [%s] ---\n" pkg-name)
          (capsule--prepare-package pkg-dir)))))
  (capsule-generate-local-autoloads))

(defun capsule-batch-compile (directory &optional native)
  "Compile DIRECTORY for a bulk build unless configured with skip-build = true.
Use `capsule-batch-build-single' to explicitly build skipped packages.
DIRECTORY is relative to the build working directory, or absolute.
This function is meant to be called from Emacs --batch mode."
  (unless noninteractive
    (error "capsule-batch-compile is only for batch mode"))

  (capsule--check-native native)
  (let ((capsule--config (capsule--read-config))
        (capsule-use-native-compile native))
    (let ((pkg-dir (expand-file-name directory)))
      (unless (file-directory-p pkg-dir)
	(error "Package directory not found: %s" pkg-dir))

      (if (capsule--skip-build-p pkg-dir)
          (message "Capsule: %s (skipped)" directory)
        (capsule--setup-load-path-all)
        (capsule--compile-package pkg-dir)))))

(defun capsule-batch-build-single (package &optional native)
  "Prepare and compile PACKAGE, optionally using NATIVE compilation.
This function is meant to be called from Emacs --batch mode."
  (unless noninteractive
    (error "capsule-batch-build-single is only for batch mode"))

  (capsule--check-native native)
  (let ((capsule-use-native-compile native))
    (capsule--build-package (expand-file-name package capsule-drones-directory))))

(defun capsule--build-package (pkg-dir)
  "Prepare and compile PKG-DIR, shared by batch builds and interactive adds.
An explicit single-package build ignores the bulk autoload skip list."
  (unless (file-directory-p pkg-dir)
    (error "Package directory not found: %s" pkg-dir))
  (let ((capsule--config (capsule--read-config)))
    (message "\n--- [%s] ---\n" (file-name-nondirectory (directory-file-name pkg-dir)))
    (capsule--prepare-package pkg-dir)
    (capsule--setup-load-path-all)
    (capsule--compile-package pkg-dir)))

(defun capsule-batch-clean ()
  "Remove selected sources' bytecode and Capsule-marked autoload files.
Do not recurse into unselected extensions or touch the shared native cache."
  (unless noninteractive (error "capsule-batch-clean is only for batch mode"))
  (require 'bytecomp)
  (let ((capsule--config (capsule--read-config)))
    (dolist (dir (append (capsule--package-directories)
                        (list (expand-file-name "lisp" user-emacs-directory))))
      (when (file-directory-p dir)
        (dolist (source (capsule--collect-el-files dir))
          (let ((bytecode (byte-compile-dest-file source)))
            (when (file-exists-p bytecode) (delete-file bytecode))))
        (let ((autoloads (expand-file-name
                          (format "%s-autoloads.el" (file-name-nondirectory dir)) dir)))
          (when (and (file-exists-p autoloads)
                     (with-temp-buffer
                       (insert-file-contents autoloads)
                       (search-forward ";; Generated by Capsule; safe for capsule-batch-clean." nil t)))
            (delete-file autoloads)))))))

;;; Interactive package management

(defun capsule--run-process (program &rest args)
  "Run PROGRAM with literal ARGS in the caller's directory; report failures."
  (with-temp-buffer
    (let ((status (apply #'process-file program nil '(t t) nil args)))
      (unless (zerop (buffer-size))
        (message "%s" (buffer-string)))
      (unless (equal status 0)
        (error "Capsule: %s failed in %s (exit %s): %S"
               program default-directory status args)))))

(defun capsule--git (&rest args)
  "Run Git in the configuration repository, stopping on failure."
  (let ((default-directory user-emacs-directory))
    (apply #'capsule--run-process "git" args)))

(defun capsule--package-path (name)
  "Return NAME's repository-relative path.
Reject names that could address files outside the package directory."
  (unless (and (not (string-empty-p name))
               (not (member name '("." "..")))
               (equal name (file-name-nondirectory name)))
    (user-error "Invalid package name: %s" name))
  (file-relative-name (expand-file-name name capsule-drones-directory)
                      user-emacs-directory))

;;;###autoload
(defun capsule-add-package (url &optional name)
  "Add a new package from git URL.
NAME defaults to the repository basename.  Only interactive calls prompt.
Adds as git submodule, generates autoloads, and compiles."
  (interactive "sPackage git URL: ")
  (let* ((default-directory user-emacs-directory)
         (parsed-name (or name
                          (and (string-match "/\\([^/]+\\)\\.git\\'" url)
                               (match-string 1 url))
                          (and (string-match "/\\([^/]+\\)/?\\'" url)
                               (match-string 1 url))))
         (pkg-name (if (called-interactively-p 'interactive)
                       (read-string "Package name: " parsed-name nil parsed-name)
                     (or parsed-name (user-error "Cannot infer package name from %s" url))))
         (pkg-path (capsule--package-path pkg-name)))
    (unless (or (not (called-interactively-p 'interactive))
                (yes-or-no-p (format "Add package '%s' from %s? " pkg-name url)))
      (user-error "Cancelled"))
    ;; Add submodule
    (message "Adding git submodule...")
    (capsule--git "submodule" "add" "--force" "--" url pkg-path)
    (capsule--git "submodule" "update" "--init" "--recursive" "--" pkg-path)
    ;; Build package
    (let ((pkg-dir (expand-file-name pkg-path user-emacs-directory)))
      (capsule--build-package pkg-dir)
      (message "Package '%s' added successfully; configure it in your init.el" pkg-name))))

;;;###autoload
(defun capsule-remove-package (name)
  "Remove package NAME.
Removes the submodule worktree and registration.
Retains Git's module metadata so existing history is not discarded."
  (interactive
   (list (completing-read "Remove package: "
                          (mapcar #'file-name-nondirectory
                                  (capsule--package-directories)))))
  (let* ((default-directory user-emacs-directory)
         (pkg-path (capsule--package-path name))
         (pkg-dir (expand-file-name pkg-path user-emacs-directory)))
    (unless (file-directory-p pkg-dir)
      (user-error "Package '%s' not found" name))
    (unless (yes-or-no-p (format "Remove package '%s'? " name))
      (user-error "Cancelled"))
    ;; Remove submodule
    (message "Removing git submodule...")
    (capsule--git "submodule" "deinit" "-f" "--" pkg-path)
    (capsule--git "rm" "-f" "--" pkg-path)
    (message "Package '%s' removed successfully!" name)
    (message "Don't forget to remove its configuration from init.el")))

(provide 'capsule)
;;; capsule.el ends here
